---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XPK.
--- DateTime: 2023/12/28 20:19
---
local SessionInfoDao = require("dao.db_ai_interview.session_info_dao")
local QuestionInfoDao = require("dao.db_ai_interview.question_info_dao")

local args = ngx.req.get_uri_args()
local session_id = args.session_id

syncutil.check_params_http(1, session_id)

SessionInfoDao.update_session_info({status = 0}, {session_id = session_id})

-- 查找所有历史问题
local question_list = QuestionInfoDao.query_question_info({"*"}, {session_id = session_id}, nil, nil, " order by id asc")
if not question_list or not next(question_list) then
    syncutil.exit_http(200, errcode.INTERNAL_ERROR, "internal server error.")
end

local history_question_and_answer = {}
for _, v in ipairs(question_list) do
    local item = {}
    table.insert(item, v.question)
    table.insert(item, v.answer)
    table.insert(item, v.topic)
    table.insert(history_question_and_answer, item)
end
-- 调用gpt
local ret, err, question_info = gpt_agent_proxy.gen_feedback(history_question_and_answer)

if ret ~= 0 then
    syncutil.exit_http(200, ret, err)
end

local data = {
    feedback_result = question_info.feedback_result,
}
syncutil.return_info(data)