---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by XPK.
--- DateTime: 2023/12/28 20:19
---
local SessionInfoDao = require("dao.db_ai_interview.session_info_dao")
syncutil.set_header()
if "OPTIONS" == ngx.req.get_method() then
    ngx.exit(ngx.HTTP_OK)
end

local args = ngx.req.get_uri_args()
local json_data = syncutil.get_body_http()
local position = json_data.position
local topic_list = json_data.topic_list
syncutil.check_params_http(1, position)
if not topic_list or not next(topic_list) then
    syncutil.exit_http(200, errcode.PARAM_INVALID, "invalid parameter")
end

local session_id = string_util.luuid()
SessionInfoDao.insert_session_info({session_id = session_id, status = 1, position = position, topic_list = cjson.encode(topic_list)})

local data = {
    session_id = session_id,
}
syncutil.return_info(data)